# Generated by Django 4.0.1 on 2025-06-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_unidade_remove_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
