# Generated by Django 4.0.1 on 2025-06-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('endpoint', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
