# Generated by Django 4.0.1 on 2024-09-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('data', models.DateField()),
                ('solicitante', models.CharField(max_length=255)),
                ('cro', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('pedido', models.CharField(db_column='pedido', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('agenda', models.CharField(max_length=100)),
                ('codigo_paciente', models.CharField(max_length=100)),
                ('paciente', models.CharField(max_length=255)),
                ('convenio', models.CharField(max_length=100)),
                ('exame', models.CharField(max_length=255)),
                ('modalidade', models.CharField(max_length=50)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Pedidos',
            },
        ),
    ]
