# Generated by Django 4.0.1 on 2025-01-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prioritario', 'Prioritário'), ('agendado', 'Agendado'), ('nao_agendado', 'Não Agendado'), ('retirada_exames', 'Retirada de Exames')], max_length=20)),
                ('unidade', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('hora_criacao', models.TimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tipo', 'unidade', 'data_criacao')},
            },
        ),
    ]
