# Generated by Django 4.0.1 on 2025-01-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='senha',
            table='Senhas',
        ),
    ]
