# Generated by Django 4.0.1 on 2025-01-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0002_alter_senha_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='senha',
            unique_together={('tipo', 'unidade', 'data_criacao', 'numero')},
        ),
    ]
