# Generated by Django 4.0.1 on 2025-06-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=50, unique=True)),
                ('codigo_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('paciente', models.CharField(max_length=255)),
                ('solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('prazo', models.CharField(blank=True, max_length=100, null=True)),
                ('agenda', models.CharField(blank=True, max_length=100, null=True)),
                ('exame', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
            ],
            options={
                'db_table': 'Modelos3D',
                'managed': False,
            },
        ),
    ]
