# Generated by Django 4.0.1 on 2024-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='Data')),
                ('status', models.CharField(db_column='Status', max_length=255)),
                ('bot_status', models.CharField(db_column='Bot_Status', max_length=100)),
                ('bot_date_time', models.CharField(db_column='Bot_DateTime', max_length=50)),
                ('resposta', models.CharField(db_column='Resposta', max_length=20)),
                ('motivo', models.CharField(db_column='Motivo', max_length=50)),
                ('obs', models.CharField(db_column='Obs', max_length=255)),
                ('voucher', models.CharField(db_column='Voucher', max_length=30)),
                ('agenda', models.CharField(db_column='Agenda', max_length=255)),
                ('pedido', models.CharField(db_column='Pedido', max_length=255, unique=True)),
                ('paciente', models.CharField(db_column='Paciente', max_length=255)),
                ('telefone', models.CharField(db_column='Telefone', max_length=20)),
            ],
            options={
                'db_table': 'SAC',
            },
        ),
        migrations.CreateModel(
            name='SACMotivosNegativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'SACMotivosNegativos',
            },
        ),
    ]
