# Generated by Django 4.0.1 on 2024-07-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sac',
            name='bot_date_time',
            field=models.CharField(blank=True, db_column='Bot_DateTime', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='bot_status',
            field=models.CharField(blank=True, db_column='Bot_Status', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='data',
            field=models.DateField(db_column='Data', max_length=100),
        ),
        migrations.AlterField(
            model_name='sac',
            name='motivo',
            field=models.CharField(blank=True, db_column='Motivo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='obs',
            field=models.CharField(blank=True, db_column='Obs', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='resposta',
            field=models.CharField(blank=True, db_column='Resposta', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='voucher',
            field=models.CharField(blank=True, db_column='Voucher', max_length=30, null=True),
        ),
    ]
