# Generated by Django 4.0.1 on 2024-07-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0002_alter_sac_bot_date_time_alter_sac_bot_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sac',
            name='id',
        ),
        migrations.AlterField(
            model_name='sac',
            name='data',
            field=models.DateField(db_column='Data'),
        ),
        migrations.AlterField(
            model_name='sac',
            name='pedido',
            field=models.CharField(db_column='Pedido', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
