# Generated by Django 4.0.1 on 2024-07-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0003_remove_sac_id_alter_sac_data_alter_sac_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sac',
            name='data',
            field=models.DateField(db_column='Data', max_length=100),
        ),
    ]
